### ISSUE TITLE
你可以学习到: 不同设计模式在 Winform 控件开发中的应用

### ISSUE THREAD

**Issue by chucklu** [iccb1013/Sheng.Winform.Controls#1]
> 对于设计模式，很多人的观念是它是用来解决大型解决方案中的问题的，但是我们在这里可以看到，设计模式不仅仅用于分解大型工程，小到一个 Winform 控件的开发，都需要具备良好的模式去帮助你分解问题，解决问题。
> 
> 例如说原型模式，我虽然能够对这种模式娓娓道来，但是一直想不出它的应用场景到底是什么，直到我发现微软在实现 DataGridView 时，应用了原型模式解决了若干问题，才豁然开朗。
> 
> 而其它诸如工厂模式，创建者模式，命令模式等，在复杂 Winform 控件的开发中，都有非常契合的应用场景。

能否把这个开源项目中，哪些地方用到了对应的设计模式，列举一下？
最好是单独写一个markdown的文档，我clone了源代码，搜索了“模式”。但是源代码里并没有注明，哪些地方应用到了设计模式
![devenv_2017-05-29_16-45-51](https://cloud.githubusercontent.com/assets/3004057/26542946/7db6a0b0-448e-11e7-94d9-147db0b77e8b.png)

**Comment by chucklu** [comment]
哦？这个建议不被采纳，不错的开源方式。
**Read The Fucking Source Code**

**Comment by iccb1013** [comment]
注意你的言辞与个人素养。

**Comment by chucklu** [comment]
你在readme里面，特意列举了3点可以学到的内容，第三点就是设计模式的应用。
所以我才会star这个项目，并且clone源码打算看一下的。
然后拿到源码，发现你并没有在源码中注明哪一块用到了设计模式。

我好心给你提了一个issue，你要是觉得不想处理，可以回复一下，然后关闭这个issue。然而，你一个回复都没有，直接把issue关闭了。这就是你的个人素养？
所以，我的理解是，你开源这个项目，就是让别人去读源码。我建议你写一个设计模式的应用文档，是我太懒了，懒得看那么多源代码，从中寻找你应用的设计模式。

read the fucking source code，出自Linux之父。我借用在这里，不过是自嘲而已。开源是你自己的事情，代码别人爱读不读。或者说难听一点，爱读就读，不想读就滚？

你的开源理念，提供源代码就足够了？
你目前开源了4个项目，所有的star数量37+24+15+9。我记得你在csdn和cnblog都发了博客的。

另外一个建议：你可以参考[kerryjiang](https://github.com/kerryjiang)的项目，看看其他人是怎么做开源的。
这个问题我就关闭了，没必要open了，反正你也不打算处理。
